version: '3.9'

services:
  web:
    build: .
    container_name: arxiv-translator
    ports:
      - 5000:5000 # flask
      - 8888:8888 # jupyter
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./tmp:/tmp
      - ./outputs:/outputs
      - ./templates:/templates
      - ./notebook:/notebook
      - .:/arxiv-translator
    working_dir: /arxiv-translator
    command: bash -c 'flask run --host=0.0.0.0 & redis-server & jupyter lab --allow-root --ip="0.0.0.0" --no-browser --ServerApp.token="a" '