filepath:
  tar_gz: /data/0_tar_gz_data  #arxivからダウンロードした*.tar.gz置き場
  raw:    /data/1_raw_data
  work:   /data/2_working_data
  output: /data/3_output_data

tex:
  pre_text: |
    % 日本語対応
    \usepackage{luatexja}
    \usepackage{luatexja-fontspec}

prompt:
  translate:
    en_to_ja: |
      texファイルを翻訳後のもので置き換えたいので、
      以下に添付するtexの断片を英語から日本語に翻訳してください。
      
      条件:
       - 翻訳結果は1つの"""で囲う。他の記号(```等)で囲ってはいけない。
       - コマンド、タグ、ラベル、記号、改行等は原文のままにする。*.texファイルとしての行数に変更がないようにする。
       - コメントアウトされた箇所はコメントアウトされたままにする。
       - texの表記法に対して一切の変更を行ってはならない。翻訳によってtexのコンパイルが失敗することは、あってはならない。
       - 人名・固有名詞・専門用語等は英語のままにする。
       - カタカナ表記は避け、英単語をそのまま用いる。英単語混じりの文章で良い。
       - 日本語の造語をしてはならない。英語混じりで良いので、無理に訳さない。
       - 翻訳は日本語の論文として適切な、"だ", "である"の文語体で行う。
       - 論文として適切なスタイルを心がける。
       - 翻訳できない箇所は無理に翻訳せず原文のままで良い。

       tex:
       """{prompt}"""